#!/usr/bin/env node

// Bundle each plugin into dist/plugins/<name>/ for marketplace distribution.
//
// Why: Claude Code's plugin marketplace pulls a directory from git into a
// cache and runs scripts directly; it doesn't run `npm install`. Plugins in
// this repo import workspace packages (@ai-plugins-cc/core,
// @ai-plugins-cc/codex-adapter, @ai-plugins-cc/shared-prompts), which won't
// resolve at runtime in the marketplace cache because there's no node_modules
// there. Bundling inlines those imports so the plugin is self-contained.
//
// Output layout (per plugin):
//   dist/plugins/<name>/
//     .claude-plugin/plugin.json
//     commands/*.md            (verbatim copies)
//     hooks/hooks.json         (verbatim)
//     agents/*.md              (verbatim)
//     prompts/*.md             (verbatim, gemini/grok only)
//     schemas/*.json           (verbatim, gemini/grok only)
//     skills/*/SKILL.md        (verbatim, gemini/grok only)
//     scripts/*.mjs            (esbuild bundles every top-level script;
//                               scripts/lib/* is inlined into whichever
//                               script imports it, not copied separately)
//     package.json             (verbatim)
//     README.md                (verbatim)
//     CHANGELOG.md             (verbatim)
//
// Run via `npm run build:plugins`. The output is committed to git so the
// marketplace install path picks it up.

import { build } from "esbuild";
import fs from "node:fs/promises";
import { existsSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const PLUGINS_DIR = path.join(REPO_ROOT, "plugins");
const DIST_ROOT = path.join(REPO_ROOT, "dist", "plugins");

const PLUGINS = ["ai", "gemini", "grok"];

// Files at the plugin root we copy verbatim (filenames). Scripts are
// handled separately. Anything not listed and not a script is ignored.
const VERBATIM_ROOT_FILES = new Set(["package.json", "README.md", "CHANGELOG.md"]);

// Top-level subdirectories that are copied verbatim (contents are static
// markdown / JSON, no JS to bundle). Tests are explicitly skipped because
// they reference workspace tooling and aren't shipped to consumers.
const VERBATIM_DIRS = new Set([
  ".claude-plugin",
  "commands",
  "hooks",
  "agents",
  "prompts",
  "schemas",
  "skills"
]);

const SKIP_DIRS = new Set(["tests", "node_modules", "dist", "src"]);

async function rmrf(target) {
  await fs.rm(target, { recursive: true, force: true });
}

async function copyTree(from, to) {
  const stat = await fs.stat(from);
  if (stat.isFile()) {
    await fs.mkdir(path.dirname(to), { recursive: true });
    await fs.copyFile(from, to);
    return;
  }
  await fs.mkdir(to, { recursive: true });
  for (const entry of await fs.readdir(from, { withFileTypes: true })) {
    if (SKIP_DIRS.has(entry.name)) continue;
    await copyTree(path.join(from, entry.name), path.join(to, entry.name));
  }
}

async function listScriptEntries(scriptsDir) {
  if (!existsSync(scriptsDir)) return [];
  const entries = [];
  for (const entry of await fs.readdir(scriptsDir, { withFileTypes: true })) {
    if (entry.name.startsWith(".")) continue;
    if (entry.isFile() && entry.name.endsWith(".mjs")) {
      entries.push(path.join(scriptsDir, entry.name));
    }
    // We deliberately do NOT recurse into scripts/lib/. Those modules are
    // imported by the top-level scripts and get inlined into each bundle.
  }
  return entries;
}

async function bundleScripts(pluginDir, distDir) {
  const scriptsSrc = path.join(pluginDir, "scripts");
  const scriptsDist = path.join(distDir, "scripts");
  const entryPoints = await listScriptEntries(scriptsSrc);
  if (entryPoints.length === 0) return { count: 0 };

  await fs.mkdir(scriptsDist, { recursive: true });

  // Bundle each entry point into a single self-contained file. esbuild
  // inlines all imports (including @ai-plugins-cc/* workspace deps) and
  // marks node:* built-ins as external.
  await build({
    entryPoints,
    outdir: scriptsDist,
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node20",
    // Preserve the entry filenames; output to the same names in dist.
    entryNames: "[name]",
    // Keep the .mjs extension on outputs (esbuild defaults to .js for ESM).
    // Hook manifests (hooks/hooks.json) and command markdown reference the
    // .mjs paths, so we must match them.
    outExtension: { ".js": ".mjs" },
    sourcemap: false,
    minify: false,
    // Keep node built-ins external; they're not bundleable anyway.
    external: ["node:*"],
    // Banner: a short note so it's obvious this file was generated.
    banner: {
      js: "// Generated by scripts/build-plugins.mjs. Do not edit by hand.\n"
    },
    logLevel: "warning"
  });

  return { count: entryPoints.length };
}

async function copyVerbatimFiles(pluginDir, distDir) {
  for (const entry of await fs.readdir(pluginDir, { withFileTypes: true })) {
    if (SKIP_DIRS.has(entry.name)) continue;
    if (entry.name === "scripts") continue; // handled by bundleScripts

    const src = path.join(pluginDir, entry.name);
    const dst = path.join(distDir, entry.name);

    if (entry.isDirectory()) {
      if (!VERBATIM_DIRS.has(entry.name)) continue;
      await copyTree(src, dst);
      continue;
    }

    if (entry.isFile() && VERBATIM_ROOT_FILES.has(entry.name)) {
      await fs.mkdir(path.dirname(dst), { recursive: true });
      await fs.copyFile(src, dst);
    }
  }
}

async function buildPlugin(name) {
  const pluginDir = path.join(PLUGINS_DIR, name);
  const distDir = path.join(DIST_ROOT, name);
  if (!existsSync(pluginDir)) {
    throw new Error(`Plugin source not found: ${pluginDir}`);
  }
  if (!statSync(pluginDir).isDirectory()) {
    throw new Error(`Plugin source is not a directory: ${pluginDir}`);
  }

  await rmrf(distDir);
  await copyVerbatimFiles(pluginDir, distDir);
  const { count } = await bundleScripts(pluginDir, distDir);
  return { name, distDir, scriptsBundled: count };
}

async function main() {
  await rmrf(DIST_ROOT);
  await fs.mkdir(DIST_ROOT, { recursive: true });

  const results = [];
  for (const name of PLUGINS) {
    const result = await buildPlugin(name);
    results.push(result);
    process.stdout.write(
      `Built ${name}: ${result.scriptsBundled} script(s) bundled → ${path.relative(REPO_ROOT, result.distDir)}\n`
    );
  }
  process.stdout.write("\nAll plugins built.\n");
}

main().catch((err) => {
  process.stderr.write(`build-plugins failed: ${err?.stack ?? err}\n`);
  process.exit(1);
});
